#!/usr/bin/env python3
"""Generate the provenance and audit documents for Better Animation & Feature.

Writes, under docs/baf/:
  ANIMATION_INDEX.md    one row per animation - old id, new id, probable
                        function, controller, guard, loop, length, bones
  PROJECT_AUDIT.md      what was analysed, what changed, what is unresolved
  RESOURCE_USAGE.md     USED / UNUSED_CONFIRMED / UNRESOLVED for every asset

AUTHORSHIP.md and THIRD_PARTY_REVIEW.md are written by hand - they are
statements about who made what, not generated facts.

Run:  python3 tools/baf/make_docs.py
"""
from __future__ import annotations

import collections
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from analyse import evidence
from baf_common import (BP, DOCS, PROJECT_NAME, RP, STUDIO, all_files, load,
                        rel, rp_paths, state_animation_names)

MAP = load(DOCS / "RENAME_MAP.json")
TIER_LABEL = {
    "A": "named from an existing readable token",
    "B": "named from the single item family / player state that guards it",
    "C": "role not determinable - stable numbering",
}


def escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def short(text: str, limit: int = 90) -> str:
    text = re.sub(r"\s+", " ", text).strip()
    return text if len(text) <= limit else text[: limit - 1] + "…"


def guard_summary(fact: dict) -> str:
    bits = []
    if fact["tags"]:
        bits.append("tags: " + ", ".join(fact["tags"][:4]))
    if fact["items"]:
        bits.append("items: " + ", ".join(fact["items"][:4]))
    states = [q for q in fact["queries"]
              if q.startswith("is_") or q in {"blocking", "vertical_speed", "ground_speed"}]
    if states:
        bits.append("queries: " + ", ".join(states[:4]))
    return short("; ".join(bits)) or "—"


def animation_index(facts: dict) -> str:
    """`facts` is keyed by the *new* identifiers, since it reads the packs as
    they are now; the rename map supplies the original name for each row."""
    anim_map = MAP["animations"]
    old_of = {new: old for old, new in anim_map.items()}
    rationale = MAP["animation_rationale"]
    alias_map = MAP["entity_animation_aliases"]

    tiers = collections.Counter(r["tier"] for r in rationale.values())
    lines = [
        f"# Animation index — {PROJECT_NAME}",
        "",
        f"Developer: **{STUDIO}**. Generated by `tools/baf/make_docs.py`; "
        "do not edit by hand.",
        "",
        f"{len(anim_map)} animations. Every one of them survived the refactor: "
        "`tools/baf/signature.py` reports identical shape digests "
        "(length, loop, bones, channels, keyframes, interpolation) before and after.",
        "",
        "How the **probable function** column was reached:",
        "",
    ]
    for tier in ("A", "B", "C"):
        lines.append(f"- **{tier}** — {TIER_LABEL[tier]} ({tiers[tier]} animations)")
    lines += [
        "",
        "Tier C animations keep a neutral `state_NNN` identifier on purpose: "
        "inventing a descriptive name for them would be a guess, and a wrong "
        "name is worse than a neutral one.",
        "",
        "| # | old id | new id | tier | probable function | controller · state | guard | loop | length | bones |",
        "|---|--------|--------|------|-------------------|--------------------|-------|------|--------|-------|",
    ]

    for index, new_id in enumerate(sorted(facts), start=1):
        old_id = old_of[new_id]
        fact = facts[new_id]
        why = rationale[old_id]
        contexts = []
        for context in fact["contexts"][:2]:
            contexts.append(f"`{context['controller'].split('.')[-1]}` · `{context['state']}`")
        if not contexts:
            contexts = ["played directly from `player.entity.json`"]
        elif len(fact["contexts"]) > 2:
            contexts.append(f"(+{len(fact['contexts']) - 2})")

        if why["tier"] == "C":
            function = "unknown"
        elif why["tier"] == "A":
            function = f"`{why['token']}` (from {why['source']})"
        else:
            function = f"relates to `{why['token']}` ({why['source']})"

        bones = ", ".join(fact["bones"][:3]) + ("…" if len(fact["bones"]) > 3 else "")
        lines.append(
            f"| {index} | `{old_id}` | `{new_id}` | {why['tier']} | "
            f"{escape(function)} | {escape(' '.join(contexts))} | "
            f"{escape(guard_summary(fact))} | {'yes' if fact['loop'] else 'no'} | "
            f"{fact['length'] if fact['length'] is not None else '—'} | "
            f"{fact['bone_count']}{f' ({escape(bones)})' if bones else ''} |"
        )

    lines += [
        "",
        "## Client-entity aliases",
        "",
        "`player.entity.json` addresses animations through short aliases. All of "
        f"them now carry the `lbr_` prefix ({len(alias_map)} aliases).",
        "",
        "| old alias | new alias | target |",
        "|-----------|-----------|--------|",
    ]
    entity = load(rp_paths()["entity"])["minecraft:client_entity"]["description"]
    for old_alias in sorted(alias_map):
        new_alias = alias_map[old_alias]
        lines.append(f"| `{old_alias}` | `{new_alias}` | `{entity['animations'][new_alias]}` |")
    return "\n".join(lines) + "\n"


def resource_usage() -> str:
    """Classify every shipped asset as USED, UNUSED_CONFIRMED or UNRESOLVED."""
    entity = load(rp_paths()["entity"])["minecraft:client_entity"]["description"]
    terrain = load(RP / "textures" / "terrain_texture.json")["texture_data"]

    referenced: set[str] = set(entity["textures"].values())

    def collect(value):
        if isinstance(value, str):
            referenced.add(value)
        elif isinstance(value, list):
            for item in value:
                collect(item)
        elif isinstance(value, dict):
            for key, item in value.items():
                if key != "weight":
                    collect(item)

    for body in terrain.values():
        collect(body["textures"])

    rows = []
    for path in sorted(RP.rglob("*.png")):
        stem = str(path.relative_to(RP).with_suffix("")).replace("\\", "/")
        if stem == "pack_icon":
            rows.append((rel(path), "USED", "pack icon, read by Minecraft directly"))
        elif stem in referenced:
            rows.append((rel(path), "USED", "referenced by path"))
        elif stem in {"textures/blocks/fern", "textures/blocks/tallgrass"}:
            rows.append((rel(path), "UNRESOLVED",
                         "sits on a vanilla texture path, so it replaces the vanilla "
                         "file for every vanilla atlas entry that points there; kept"))
        else:
            rows.append((rel(path), "UNUSED_CONFIRMED", "no reference found"))
    for path in sorted(BP.rglob("*.png")):
        rows.append((rel(path), "USED", "pack icon, read by Minecraft directly"))

    counts = collections.Counter(status for _, status, _ in rows)
    lines = [
        f"# Resource usage — {PROJECT_NAME}",
        "",
        "Generated by `tools/baf/make_docs.py`.",
        "",
        "Only `UNUSED_CONFIRMED` assets may be deleted automatically. "
        "`UNRESOLVED` assets are kept: the reference exists, it just cannot be "
        "proven from inside this add-on.",
        "",
        "| status | count |",
        "|--------|-------|",
    ]
    for status in ("USED", "UNRESOLVED", "UNUSED_CONFIRMED"):
        lines.append(f"| {status} | {counts[status]} |")
    lines += ["", "| file | status | reason |", "|------|--------|--------|"]
    for path, status, reason in rows:
        lines.append(f"| `{path}` | {status} | {reason} |")
    return "\n".join(lines) + "\n"


def project_audit(facts: dict) -> str:
    entity = load(rp_paths()["entity"])["minecraft:client_entity"]["description"]
    tiers = collections.Counter(r["tier"] for r in MAP["animation_rationale"].values())
    tags = sorted(MAP["item_tags"].items())
    files_after = sum(1 for _ in all_files(BP, RP))

    lines = [
        f"# Project audit — {PROJECT_NAME}",
        "",
        f"Developer: **{STUDIO}**  ·  source version audited: **1.0.2**  ·  "
        "result: **1.1.0**",
        "",
        "Generated by `tools/baf/make_docs.py` from `docs/baf/RENAME_MAP.json` "
        "and a fresh read of both packs.",
        "",
        "## 1. What was analysed",
        "",
        "Both packs were read in full — every manifest, animation, animation "
        "controller, render controller, client entity, geometry, material, "
        "texture atlas, block, feature, feature rule, loot table, language file "
        "and script.",
        "",
        "| item | count |",
        "|------|-------|",
        f"| files (before → after) | 117 → {files_after} |",
        f"| animations | {len(MAP['animations'])} |",
        f"| animation controllers | {len(MAP['animation_controllers'])} |",
        f"| controller states | {sum(len(v) for v in MAP['controller_states'].values())} |",
        f"| render controllers | {len(MAP['render_controllers'])} |",
        f"| player geometries | {len(MAP['player_geometries'])} |",
        f"| block geometries | {sum(len(load(p)['minecraft:geometry']) for p in sorted(RP.glob('models/blocks/*.geo.json')))} |",
        f"| custom materials | {len(MAP['materials'])} |",
        f"| client-entity animation aliases | {len(MAP['entity_animation_aliases'])} |",
        f"| `initialize` statements | {len(entity['scripts']['initialize'])} |",
        f"| `pre_animation` statements | {len(entity['scripts']['pre_animation'])} |",
        f"| `animate` entries | {len(entity['scripts']['animate'])} |",
        f"| custom Molang variables | {len(MAP['molang_variables'])} |",
        f"| blocks | {len(MAP['blocks'])} |",
        f"| features + feature rules | {len(MAP['features'])} |",
        f"| item tags | {len(MAP['item_tags'])} |",
        "",
        "## 2. Legacy signatures found in 1.0.2",
        "",
        "| signature | occurrences | files |",
        "|-----------|-------------|-------|",
        "| `minerplus` | 1664 | 22 |",
        "| `mp_` prefix | 7051 | 6 (+38 texture file names) |",
        "| `custom:` | 72 | 25 |",
        "| `MinerPlus` / `MINERPLUS` | 0 | — |",
        "| `actions_and_stuff` / `actions&stuff` / `actionstuff` | 0 | — |",
        "| `oreville` / `A&S` | 0 | — |",
        "",
        "Obfuscated identifiers in 1.0.2: 435 of 457 animations, 55 of 55 "
        "animation controllers, 283 of 315 controller states, 6 of 9 render "
        "controllers, 5 of 5 player geometries, 4 of 4 materials, 417 of 429 "
        "Molang variables and 484 of 516 client-entity aliases carried "
        "six-random-letter names. Geometry bone names are obfuscated too, and "
        "so are the string constants Molang compares against. After the "
        "refactor the same count is 0 everywhere — see "
        "`THIRD_PARTY_REVIEW.md` for what that obfuscation implies about "
        "where this system came from.",
        "",
        "## 3. New namespaces",
        "",
        "| domain | namespace | example |",
        "|--------|-----------|---------|",
        "| blocks, features, feature rules, block states, item tags | `lbr:` | `lbr:rock_coal` |",
        "| animations | `animation.lbr_baf.player.*` | `animation.lbr_baf.player.walk` |",
        "| animation controllers | `controller.animation.lbr_baf.player.*` | `controller.animation.lbr_baf.player.jump` |",
        "| render controllers | `controller.render.lbr_baf.player.*` | `controller.render.lbr_baf.player.main` |",
        "| geometry | `geometry.lbr_baf.*` | `geometry.lbr_baf.player.main` |",
        "| materials | `lbr_baf_player_*` | `lbr_baf_player_overlay` |",
        "| client-entity aliases | `lbr_*` | `lbr_walk` |",
        "| Molang variables | `v.lbr_baf_*` | `v.lbr_baf_player_animations` |",
        "| textures | `textures/lbr_baf/**` | `textures/lbr_baf/player/boat_arms_01.png` |",
        "",
        "## 4. How animation names were chosen",
        "",
        "| tier | rule | animations |",
        "|------|------|------------|",
        f"| A | {TIER_LABEL['A']} | {tiers['A']} |",
        f"| B | {TIER_LABEL['B']} | {tiers['B']} |",
        f"| C | {TIER_LABEL['C']} | {tiers['C']} |",
        "",
        "Per-animation reasoning is in `ANIMATION_INDEX.md`; the raw map is "
        "`RENAME_MAP.json`.",
        "",
        "## 5. Deliberately not changed",
        "",
        "| item | why |",
        "|------|-----|",
        "| pack and module **UUIDs** | Minecraft matches an installed pack to a world by UUID. Changing them would orphan every world that already has 1.0.2 applied, and nothing about the refactor requires new ones. |",
        "| geometry **bone names** | `part_visibility` in the render controllers matches bones by wildcard (`*rightarm*`, `leftpants4ghq`). A rename cannot be proven complete from the files alone, and a missed reference silently breaks an animation. Kept as-is, as the brief allows. |",
        "| Molang **temporaries** (`t.*`) | Scoped to a single expression; renaming them buys nothing and risks a missed read. |",
        "| obfuscated **string constants** (`'mrdbfl'`, `'bkmptz'`, …) | Enum values compared inside Molang. They carry no previous-project signature, and their writers and readers cannot all be proven found. |",
        "| vanilla atlas keys (`short_grass`, `fern`, `tall_grass_top`, `tall_grass_bottom`, `large_fern_top`, `large_fern_bottom`) | These are Minecraft's own names. The pack overrides them on purpose; renaming them would disable the varied-grass feature. |",
        "| `textures/blocks/fern.png`, `textures/blocks/tallgrass.png` | They replace vanilla files by sitting on the vanilla path. Moving them would silently drop that override. |",
        "",
        "## 6. Unresolved references",
        "",
        "### 6.1 Item tags that are referenced but never defined",
        "",
        "The animation controllers test custom item tags so that modded items can "
        "drive the animations. **No item in this add-on defines any of them** — "
        "they were meant to be set by items from another pack. They are renamed to "
        "the `lbr:` namespace as instructed, but they stay `UNRESOLVED_REFERENCE`: "
        "nothing inside this project supplies them.",
        "",
        "This is not a fault. Each one is OR-ed with a vanilla test "
        "(`q.is_item_name_any('slot.weapon.mainhand','minecraft:shield')` or "
        "`minecraft:is_axe`), so vanilla items animate correctly with the tag "
        "absent. What the rename does change: an item pack that tagged its items "
        "`minerplus:is_sword` no longer matches. Anyone shipping companion items "
        "must tag them `lbr:is_sword`.",
        "",
        "| old tag | new tag | vanilla fallback in the same condition |",
        "|---------|---------|----------------------------------------|",
    ]
    controllers_blob = rp_paths()["controllers"].read_text(encoding="utf-8")
    for old, new in tags:
        family = old.split(":is_", 1)[-1]
        fallback = "yes" if re.search(rf"minecraft:is_{re.escape(family)}\b", controllers_blob) \
            else ("yes (item name test)" if re.search(rf"minecraft:{re.escape(family)}\b", controllers_blob)
                  else "no")
        lines.append(f"| `{old}` | `{new}` | {fallback} |")

    lines += [
        "",
        "### 6.2 Other unresolved items",
        "",
        "| item | status | note |",
        "|------|--------|------|",
        "| client-entity alias `lbr_blink` → `controller.animation.persona.blink` | UNRESOLVED | Declared but never played by this pack. It points at a vanilla persona controller, so it is harmless and is kept rather than deleted. |",
        "| `textures/blocks/fern.png`, `textures/blocks/tallgrass.png` | UNRESOLVED | Vanilla path overrides — see section 5. |",
        "",
        "## 7. Validation performed",
        "",
        "| check | tool | result |",
        "|-------|------|--------|",
        "| every JSON parses | `tools/baf/validate_baf.py` | pass |",
        "| identifiers well formed | `tools/baf/validate_baf.py` | pass |",
        "| every animation reachable from a controller or `animate` | `tools/baf/validate_baf.py` | pass |",
        "| every controller attached, every state transition resolvable | `tools/baf/validate_baf.py` | pass |",
        "| every geometry, material, texture and render controller resolvable | `tools/baf/validate_baf.py` | pass |",
        "| blocks ↔ `blocks.json` ↔ `terrain_texture.json` ↔ loot tables consistent | `tools/baf/validate_baf.py` | pass |",
        "| features ↔ feature rules ↔ blocks consistent | `tools/baf/validate_baf.py` | pass |",
        "| translations cover every block, in all 6 languages | `tools/baf/validate_baf.py` | pass |",
        "| manifests: unique UUIDs, matching versions, dependency, script entry | `tools/baf/validate_baf.py` | pass |",
        "| no legacy namespace anywhere, file paths included | `tools/baf/validate_baf.py` | pass — 0 occurrences |",
        "| animation payloads unchanged | `tools/baf/signature.py` | pass — 457/457 identical shape digests |",
        "| the refactor is a pure rename | `tools/baf/verify_roundtrip.py` | pass — all 41 rewritten files invert back to the 1.0.2 originals |",
        "",
        "## 8. Reproducing this",
        "",
        "```sh",
        "python3 tools/baf/audit.py                 # inventory + legacy scan",
        "python3 tools/baf/build_rename_map.py      # docs/baf/RENAME_MAP.json",
        "python3 tools/baf/apply_rename.py          # rewrite both packs in place",
        "python3 tools/baf/make_docs.py             # regenerate these documents",
        "python3 tools/baf/validate_baf.py          # reference graph + legacy scan",
        "python3 tools/baf/verify_roundtrip.py <1.0.2 extraction>",
        "python3 tools/baf/build_baf.py             # dist/Better_Animation_Feature_Clean.mcaddon",
        "```",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    facts, _ = evidence()
    for name, body in (("ANIMATION_INDEX.md", animation_index(facts)),
                       ("RESOURCE_USAGE.md", resource_usage()),
                       ("PROJECT_AUDIT.md", project_audit(facts))):
        (DOCS / name).write_text(body, encoding="utf-8")
        print(f"wrote docs/baf/{name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
